### List all rooms - deep read
GET http://localhost:4004/v2/hostel/Rooms?
&$expand=Students

### Create Rooms - insert
POST http://localhost:4004/v2/hostel/Rooms
Content-Type: application/json

{
    "RoomNumber": "1"
}

### Update Rooms - update
PATCH  http://localhost:4004/v2/hostel/Rooms('1')
Content-Type: application/json

{
    "RoomNumber": "1",
    "Capacity": 4,
    "ActionIndicator": "UPDATE"
}


### Try to get the Rooms
GET http://localhost:4004/v2/hostel/Rooms


### Create Students - deep insert
POST http://localhost:4004/v2/hostel/Students
Content-Type: application/json

{
    "FirstName": "Stanislau7",
    "LastName": "Pyrkin7",
    "Email": "Stanislau.pyrkin@gmail.com",
    "City": "Minsk",
    "AddressLine": "Knorina 6b, 56",
    "ZipCode": "213410",
    "Phones": [
        {
            "PhoneNumber": "+375298639126",
            "PhoneType": "MOBILE"
        }
    ],
    "Notes": []
}

### Try to update the Student
PATCH http://localhost:4004/v2/hostel/Students(5964950a-ca5b-4974-80c8-aa2580e07007)
Content-Type: application/json

{
    "FirstName": "Stanislau",
    "LastName": "Pyrkin",
    "Email": "Stanislau.pyrkin@gmail.com",
    "City": "Minsk",
    "AddressLine": "Knorina 6b, 56",
    "ZipCode": "213410",
    "Phones": [
        {
            "PhoneNumber": "+375298639126",
            "PhoneType": "MOBILE"
        }
    ],
    "Notes": [],
    "Room_RoomNumber": "1"
}

### Try to get the Orders
GET http://localhost:4004/v2/hostel/Students

### Try to get the Orders

PATCH http://localhost:4004/v2/hostel/Rooms('1')
Content-Type: application/json

{
    "RoomNumber": "1",
    "Capacity": 3,
    "EmptyPlaces": 3,
    "ActionIndicator": "UPDATE",
    "Students": [
        {
            "ID": "78673bd6-a1d9-4e14-9532-e658d83e940b",
            "FirstName": "UPDATE",
            "LastName": "UPDATE",
            "Email": "Stanislau.pyrkin@gmail.com",
            "City": "Minsk",
            "AddressLine": "Knorina 6b, 56",
            "ZipCode": "213410",
            "Phones": [
                {
                    "PhoneNumber": "+375298639126",
                    "PhoneType": "MOBILE"
                }
            ],
            "Notes": [],
            "ActionIndicator": "DELETE ",
            "Room_RoomNumber": "1"
        }
        #,
        # {
        #     "FirstName": "UPDATE",
        #     "LastName": "UPDATE",
        #     "Email": "Stanislau.pyrkin@gmail.com",
        #     "City": "Minsk",
        #     "AddressLine": "Knorina 6b, 56",
        #     "ZipCode": "213410",
        #     "Phones": [
        #         {
        #             "PhoneNumber": "+375298639126",
        #             "PhoneType": "MOBILE"
        #         }
        #     ],
        #     "Notes": [],
        #     "ActionIndicator": "CREATE"
        # }
    ]
}